title: MySchoolHub - News
email: hausercj77@gmail.com
description: > 
  Articles about books, games, anime, coding, and random stuff we find interesting.
baseurl: "" # leave empty for GitHub Pages
url: "https://myschoolhub.github.io/news" # replace with your GitHub Pages URL

theme: minima
plugins:
  - jekyll-feed
